<script setup>
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'

const route = useRoute()
const router = useRouter()
const drawerOpen = ref(false)
const imageSources = {
  hamburguesaPortada: 'https://images.unsplash.com/photo-1550547660-d9450f859349',
  hamburguesaChef: 'https://images.unsplash.com/photo-1550317138-10000687a72b',
  hamburguesaPollo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
  hamburguesaVeggie: 'https://images.unsplash.com/photo-1520072959219-c595dc870360',
  perroPortada: 'https://images.unsplash.com/photo-1612392062631-94dd858cba88',
  pizzaPortada: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002',
  pizzaChef: 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
  pizzaPollo: 'https://images.unsplash.com/photo-1579751626657-72bc17010498',
  bebidaPortada: 'https://images.unsplash.com/photo-1544145945-f90425340c7e',
  limonadaChef: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd',
  miloFrio: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699',
  jugoMango: 'https://images.unsplash.com/photo-1546173159-315724a31696',
  sodaFrutosRojos: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc',
  postrePortada: 'https://images.unsplash.com/photo-1551024506-0bccd828d307',
  brownieChef: 'https://plus.unsplash.com/premium_photo-1716152295675-595f7a5a1d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YnJvd25pZXxlbnwwfHwwfHx8MA%3D%3D',
  brownieClasico: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c',
  cheesecakeFrutosRojos: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad',
  churros: 'https://images.unsplash.com/photo-1624371414361-e670edf4898d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2h1cnJvfGVufDB8fDB8fHww',
  copaFrutas: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea',
  camiloRojas: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
  lauraMendez: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
  andresDiaz: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
  hamburguesaClasica: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90',
  hamburguesaTocineta: 'https://images.unsplash.com/photo-1550547660-d9450f859349',
  hamburguesaPolloCrunch: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330',
  perroChef: 'https://images.unsplash.com/photo-1613482084286-41f25b486fa2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cGVycm9zJTIwY2FsaWVudGVzfGVufDB8fDB8fHww',
  perroMexicano: 'https://images.unsplash.com/photo-1627054248949-21f77275a15f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHBlcnJvcyUyMGNhbGllbnRlc3xlbnwwfHwwfHx8MA%3D%3D',
  perroRanchero: 'https://images.unsplash.com/photo-1695089028533-c6e9cf1ee3cb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHBlcnJvcyUyMGNhbGllbnRlc3xlbnwwfHwwfHx8MA%3D%3D',
  perroVeggie: 'https://plus.unsplash.com/premium_photo-1683121324502-94bd9fa0202e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8cGVycm9zJTIwY2FsaWVudGVzJTIwdmVnYW5vfGVufDB8fDB8fHww',
  pizzaPepperoni: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHBpenphfGVufDB8fDB8fHww',
  pizzaCarnes: 'https://images.unsplash.com/photo-1613564834361-9436948817d1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cGl6emF8ZW58MHx8MHx8fDA%3D',
  limonadaNatural: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGltb25hZGF8ZW58MHx8MHx8fDA%3D',
  mediterranea: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHBpenphfGVufDB8fDB8fHww',
  perroEspecial: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHBlcnJvcyUyMGNhbGllbnRlc3xlbnwwfHwwfHx8MA%3D%3D',
  promocionesHero: 'https://images.unsplash.com/photo-1567019329121-8e80a510a5c5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudGUlMjBlc3F1aW5lcm98ZW58MHx8MHx8fDA%3D',
  promocionHamburguesas: 'https://plus.unsplash.com/premium_photo-1683619761468-b06992704398?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8MiUyMGhhbWJ1cmd1ZXNhc3xlbnwwfHwwfHx8MA%3D%3D',
  promocionPizza: 'https://media.istockphoto.com/id/1179675467/es/foto/vaso-de-coca-y-pizza.webp?a=1&b=1&s=612x612&w=0&k=20&c=Xjh-hrzx7JGE43n4ga1cwhF3R1LYTVeVIo27CXSt5f8=',
}
const image = (id, width = 800) => `${imageSources[id]}${imageSources[id].includes('?') ? '&' : '?'}auto=format&fit=crop&w=${width}&q=85`

const categories = [
  { slug: 'hamburguesas', label: 'Hamburguesas', icon: 'lunch_dining', description: 'Carne a la parrilla, pan suave y combinaciones que se quedan en la memoria.', cover: image('hamburguesaPortada', 1800), chef: 'La Alex Doble', chefDescription: 'Doble carne Angus, cheddar, tocineta crocante y nuestra salsa secreta.', chefPrice: '$32.900', chefImage: image('hamburguesaChef', 900), products: [['La Clásica', 'Carne Angus, cheddar, lechuga, tomate y salsa de la casa.', '$18.500', 'Más pedido', image('hamburguesaClasica')], ['BBQ Tocineta', 'Carne a la parrilla, tocineta, cebolla crispy y BBQ ahumada.', '$23.900', 'Nuevo', image('hamburguesaTocineta')], ['Pollo Crunch', 'Pollo apanado, queso suizo, repollo morado y mayo chipotle.', '$21.500', 'Picante', image('hamburguesaPolloCrunch')], ['Veggie Verde', 'Portobello, aguacate, rúgula, tomate y mayonesa de ajo.', '$20.900', 'Vegetariano', image('hamburguesaVeggie')]] },
  { slug: 'perros', label: 'Perros', icon: 'fastfood', description: 'El clásico de la calle con toppings generosos y el toque único de La Esquina.', cover: image('perroPortada', 1800), chef: 'Perro Callejero', chefDescription: 'Salchicha alemana, tocineta, queso fundido, papitas y salsas de la casa.', chefPrice: '$22.900', chefImage: image('perroChef', 900), products: [['Perro Especial', 'Salchicha, tocineta, queso, papa ripio y salsas.', '$16.900', 'Más pedido', image('perroEspecial')], ['Perro Mexicano', 'Jalapeños, guacamole, pico de gallo y salsa chipotle.', '$19.900', 'Picante', image('perroMexicano')], ['Perro Ranchero', 'Chorizo, maíz dulce, queso costeño y salsa ranch.', '$18.500', 'Nuevo', image('perroRanchero')], ['Perro Veggie', 'Salchicha vegetal, cebolla caramelizada y mostaza dulce.', '$17.900', 'Vegetariano', image('perroVeggie')]] },
  { slug: 'pizzas', label: 'Pizzas', icon: 'local_pizza', description: 'Masa artesanal, borde dorado y mucho sabor para compartir sin afán.', cover: image('pizzaPortada', 1800), chef: 'Pizza La Esquina', chefDescription: 'Salsa napolitana, mozzarella, pepperoni, albahaca y aceite de oliva.', chefPrice: '$29.900', chefImage: image('pizzaChef', 900), products: [['Pepperoni', 'Mozzarella, pepperoni artesanal, salsa napolitana y orégano.', '$24.900', 'Más pedido', image('pizzaPepperoni')], ['Carnes BBQ', 'Tocineta, pepperoni, carne molida y salsa BBQ ahumada.', '$28.900', 'Nuevo', image('pizzaCarnes')], ['Pollo Pesto', 'Pollo, mozzarella, tomate cherry, pesto y rúgula fresca.', '$27.900', '', image('pizzaPollo')], ['Mediterránea', 'Mozzarella, champiñones, aceitunas, pimentón y albahaca.', '$25.900', 'Vegetariano', image('mediterranea')]] },
  { slug: 'bebidas', label: 'Bebidas', icon: 'local_drink', description: 'Opciones frías para acompañar cada antojo y refrescar el momento.', cover: image('bebidaPortada', 1800), chef: 'Limonada Hierbabuena', chefDescription: 'Limonada natural, hierbabuena fresca, hielo y el punto exacto de dulce.', chefPrice: '$9.900', chefImage: image('limonadaChef', 900), products: [['Limonada Natural', 'Limón recién exprimido, hielo y agua filtrada.', '$7.500', 'Más pedido', image('limonadaNatural')], ['Milo Frío', 'Milo, leche fría, hielo y crema batida.', '$10.900', 'Nuevo', image('miloFrio')], ['Jugo de Mango', 'Mango dulce, agua y hielo. Sin azúcar añadida.', '$8.900', '', image('jugoMango')], ['Soda Frutos Rojos', 'Soda, frutos rojos, limón y hierbabuena.', '$11.900', 'Vegetariano', image('sodaFrutosRojos')]] },
  { slug: 'postres', label: 'Postres', icon: 'cake', description: 'Un final feliz: dulces caseros para cerrar la comida con una sonrisa.', cover: image('postrePortada', 1800), chef: 'Brownie de la Casa', chefDescription: 'Brownie tibio de chocolate, helado de vainilla y salsa de arequipe.', chefPrice: '$13.900', chefImage: image('brownieChef', 900), products: [['Brownie Clásico', 'Chocolate oscuro, nueces, helado de vainilla y arequipe.', '$12.900', 'Más pedido', image('brownieClasico')], ['Cheesecake Frutos Rojos', 'Base de galleta, crema de queso y frutos rojos.', '$14.900', 'Nuevo', image('cheesecakeFrutosRojos')], ['Churros', 'Churros crujientes, azúcar y salsa de chocolate.', '$11.900', '', image('churros')], ['Copa de Frutas', 'Frutas de temporada, yogur griego y granola casera.', '$10.900', 'Vegetariano', image('copaFrutas')]] },
]

const currentCategory = computed(() => categories.find((item) => item.slug === route.path.slice(1)) || categories[0])
const isAbout = computed(() => route.path === '/nosotros')
const isPromos = computed(() => route.path === '/promociones')
function navigate(path) { router.push(path); drawerOpen.value = false }
</script>

<template>
  <q-layout view="hHh Lpr fFf" class="restaurant-app">
    <q-header class="topbar"><q-toolbar class="topbar__inner"><q-btn flat round icon="menu" class="mobile-menu" aria-label="Abrir menú" @click="drawerOpen = !drawerOpen" /><button class="brand" @click="navigate('/')"><span class="brand__mark">A</span> LA ESQUINA<span class="brand__dot">.</span></button><q-space /><nav class="desktop-nav"><button v-for="category in categories" :key="category.slug" :class="{ active: route.path === (category.slug === 'hamburguesas' ? '/' : `/${category.slug}`) }" @click="navigate(category.slug === 'hamburguesas' ? '/' : `/${category.slug}`)">{{ category.label }}</button><button :class="{ active: isPromos }" @click="navigate('/promociones')">Promociones</button><button :class="{ active: isAbout }" @click="navigate('/nosotros')">Nosotros</button></nav></q-toolbar></q-header>
    <q-drawer v-model="drawerOpen" bordered class="mobile-drawer"><div class="drawer-brand"><span class="brand__mark">A</span> LA ESQUINA<span class="brand__dot">.</span></div><q-list padding><q-item v-for="category in categories" :key="category.slug" clickable :active="route.path === (category.slug === 'hamburguesas' ? '/' : `/${category.slug}`)" active-class="drawer-active" @click="navigate(category.slug === 'hamburguesas' ? '/' : `/${category.slug}`)"><q-item-section avatar><q-icon :name="category.icon" /></q-item-section><q-item-section>{{ category.label }}</q-item-section></q-item><q-item clickable @click="navigate('/promociones')"><q-item-section avatar><q-icon name="local_offer" /></q-item-section><q-item-section>Promociones</q-item-section></q-item><q-item clickable @click="navigate('/nosotros')"><q-item-section avatar><q-icon name="groups" /></q-item-section><q-item-section>Nosotros</q-item-section></q-item></q-list></q-drawer>
    <q-page-container><q-page>
      <template v-if="!isAbout && !isPromos"><section class="category-hero" :style="{ backgroundImage: `url(${currentCategory.cover})` }"><div class="category-hero__shade"></div><div class="page-width category-hero__content"><p class="eyebrow">HECHO AL MOMENTO · 100% SABOR</p><h1>{{ currentCategory.label }}</h1><p>{{ currentCategory.description }}</p></div></section><main class="page-width menu-content"><div class="section-heading"><div><p class="eyebrow eyebrow--red">NUESTRO MENÚ</p><h2>Elige tu favorito</h2></div><span class="section-note">Preparado con cariño en cada pedido</span></div><section class="chef-pick"><img :src="currentCategory.chefImage" :alt="currentCategory.chef" /><div class="chef-pick__body"><p class="eyebrow eyebrow--yellow">RECOMENDACIÓN DEL CHEF</p><h2>{{ currentCategory.chef }}</h2><p>{{ currentCategory.chefDescription }}</p><strong>{{ currentCategory.chefPrice }}</strong></div></section><div class="product-grid"><article v-for="product in currentCategory.products" :key="product[0]" class="product-card"><div class="product-card__image"><img :src="product[4]" :alt="product[0]" loading="lazy" /><q-badge v-if="product[3]" color="primary" floating>{{ product[3] }}</q-badge></div><div class="product-card__body"><h3>{{ product[0] }}</h3><p>{{ product[1] }}</p><div class="product-card__footer"><strong>{{ product[2] }}</strong></div></div></article></div></main></template>
      <template v-else-if="isPromos"><section class="simple-hero simple-hero--promos" :style="{ backgroundImage: `url(${image('promocionesHero')})` }"><div class="simple-hero__shade"></div><div class="page-width simple-hero__content"><p class="eyebrow eyebrow--yellow">PARA COMPARTIR</p><h1>Promociones</h1><p>Más sabor, más amigos y precios para volver por otro.</p></div></section><main class="page-width promo-content"><div class="promo-grid"><article class="promo-card promo-card--dark"><img :src="image('promocionHamburguesas')" alt="Dos hamburguesas con papas" /><div class="promo-card__body"><span>COMBO DE LA SEMANA</span><h2>2 hamburguesas + papas + 2 bebidas</h2><strong>$49.900</strong></div></article><article class="promo-card"><img :src="image('promocionPizza')" alt="Pizza mediana y dos bebidas" /><div class="promo-card__body"><span>PLAN PARA DOS</span><h2>Pizza mediana + 2 bebidas</h2><strong>$34.900</strong></div></article></div></main></template>
      <template v-else><section class="simple-hero simple-hero--about"><div class="page-width"><p class="eyebrow eyebrow--yellow">DESDE 2018</p><h1>Nosotros</h1><p>Comida honesta, barrio y ganas de verte sonreír.</p></div></section><main class="page-width about-content"><section class="about-story"><div><p class="eyebrow eyebrow--red">NUESTRA HISTORIA</p><h2>Una esquina con mucho corazón</h2><p>La Esquina nació de una cocina familiar y una idea sencilla: servir comida rápida con ingredientes reales, porciones generosas y trato de casa. Hoy seguimos cocinando cada pedido como si fuera para nuestros amigos.</p></div><div class="about-details"><p><strong>Encuéntranos</strong><br />Cra. 7 # 45-18, Bogotá</p><p><strong>Horarios</strong><br />Lun a jue 12:00 m - 10:00 p. m.<br />Vie y sáb 12:00 m - 11:00 p. m.</p><p><strong>Pedidos</strong><br />+57 310 555 0188 · WhatsApp</p></div></section><section class="team"><p class="eyebrow eyebrow--red">EL EQUIPO</p><h2>Las personas detrás del sabor</h2><div class="team-grid"><div><img :src="image('camiloRojas', 500)" alt="Camilo Rojas, chef" /><h3>Camilo Rojas</h3><p>Chef y fundador</p></div><div><img :src="image('lauraMendez', 500)" alt="Laura Méndez, cajera" /><h3>Laura Méndez</h3><p>Caja y atención</p></div><div><img :src="image('andresDiaz', 500)" alt="Andrés Díaz, domiciliario" /><h3>Andrés Díaz</h3><p>Domicilios</p></div></div></section></main></template>
    </q-page></q-page-container><footer class="footer"><div class="page-width"><strong>LA ESQUINA<span class="brand__dot">.</span></strong><span>Comida rápida, hecha con calma.</span><span>© 2026 · Bogotá, Colombia</span></div></footer>
  </q-layout>
</template>
